# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7c3c01f070ba1a78de9671ab45cb8d83"
name = "Image Alt Fix"
application_url = "https://image-alt-fix.vercel.app"
embedded = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/api/webhooks"

  # Mandatory privacy compliance webhooks for App Store apps.
  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/api/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_files"

[auth]
redirect_urls = [ "https://image-alt-fix.vercel.app/api/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
